INSERT INTO
    PUBLIC.USERS (
    ID,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    EMAIL,
    PASSWORD,
    IS_BLOCKED,
    IS_DELETED,
    LOGIN_ATTEMPTS_COUNT,
    TOKEN,
    REFRESH_TOKEN,
    GOOGLE_TOKEN,
    GOOGLE_PICTURE_URL,
    FRONTEND_THEME,
    GENETIC_DATA_ID,
    CREATED_AT,
    CREATED_BY,
    UPDATED_AT,
    UPDATED_BY
)
VALUES
    (
        UUID_GENERATE_V4 (),
        'Andi',
        NULL,
        'Thomaj',
        'andi.dev94@gmail.com',
        'test',
        FALSE,
        FALSE,
        1,
        'token',
        'refresh_token',
        'google_token',
        'picture_url',
        'black',
        NULL,
        NOW(),
        'created_by',
        NULL,
        'updated_by'
    );